/**
 * Created by Alex on 16/8/19.
 */
//活动
export const GET_ACTIVITY_LIST = 'GET_ACTIVITY_LIST'
export const GET_ACTIVITY_INFO = 'GET_ACTIVITY_INFO'
export const GET_ACTIVITY_SIGN_LIST = 'GET_ACTIVITY_SIGN_LIST'
export const BOOK_ACTIVITY = 'BOOK_ACTIVITY'
export const ZAN_ACTIVITY = 'ZAN_ACTIVITY'
export const SIGN_UP_ACTIVITY = 'SIGN_ACTIVITY'
export const GET_ACTIVITY_MESSAGE_LIST = 'GET_ACTIVITY_MESSAGE_LIST'
export const COMMIT_ACTIVITY_MESSAGE = 'COMMIT_ACTIVITY_MESSAGE'
export const GET_RECORD = 'GET_RECORD'

export const GET_USER_INFO = 'GET_USER_INFO'

export const GET_ONGOING_ACTIVITY_LIST = 'GET_ONGOING_ACTIVITY_LIST'
export const GET_COMPLETED_ACTIVITY_INFO = 'GET_COMPLETED_ACTIVITY_LIST'
export const GET_COMPLETED_ACTIVITY_TIMELINE = 'GET_COMPLETED_ACTIVITY_TIMELINE'

export const GET_CHILD_INFO = 'GET_CHILD_INFO'
export const GET_USER_UP = 'GET_USER_UP'
export const POST_CHILD_UPDATE = 'POST_CHILD_UPDATE'
export const POST_ALTER_CHILD_INFO = 'POST_ALTER_CHILD_INFO'
export const DELETE_CHILD_INFO = 'DELETE_CHILD_INFO'

export const SET_EDIT_CHILD_INFO = 'SET_CHILD_INFO'
export const REMOVE_EDIT_CHILD_INFO = 'REMOVE_CHILD_INFO'

export const SET_SIGN_INFO = "SET_SIGN_INFO"

export const UNSHIFT_SIGN_INFO = 'UNSHIFT_SIGN_INFO'

export const SET_LAST_ACTIVITY_BOOK_INFO = 'SET_LAST_ACTIVITY_BOOK_INFO'
export const SET_LAST_ACTIVITY_SIGN_INFO = 'SET_LAST_ACTIVITY_SIGN_INFO'
export const SET_LAST_COMMENT_INFO = 'SET_LAST_COMMENT_INFO'

export const PUSH_LAST_COMMENT_SIGN_INFO ='PUSH_LAST_COMMENT_SIGN_INFO'