/**
 * Created by Alex on 16/8/19.
 */
//活动
export const GET_ACTIVITY_LIST = 'GET_ACTIVITY_LIST'
export const GET_ACTIVITY_INFO = 'GET_ACTIVITY_INFO'
export const GET_ACTIVITY_SIGN_LIST = 'GET_ACTIVITY_SIGN_LIST'
export const BOOK_ACTIVITY = 'BOOK_ACTIVITY'
export const ZAN_ACTIVITY = 'ZAN_ACTIVITY'
export const SIGN_UP_ACTIVITY = 'SIGN_ACTIVITY'
export const GET_ACTIVITY_MESSAGE_LIST = 'GET_ACTIVITY_MESSAGE_LIST'
export const COMMIT_ACTIVITY_MESSAGE = 'COMMIT_ACTIVITY_MESSAGE'

export const GET_USER_INFO = 'GET_USER_INFO'
export const GET_ONGOING_ACTIVITY_LIST = 'GET_ONGOING_ACTIVITY_LIST'
export const GET_COMPLETED_ACTIVITY_INFO = 'GET_COMPLETED_ACTIVITY_LIST'
export const GET_COMPLETED_ACTIVITY_TIMELINE = 'GET_COMPLETED_ACTIVITY_TIMELINE'